### PR TITLE
New pretty indentation of HTML outputs

### PR DESCRIPTION
**Pull request by vonavi**
Hi guys!

At last, I've finished code which simplifies the indentation and output accumulation of Org files. All examples passed correctly (HTML and Textile examples, code syntax highlighting), and, on my opinion, look pretty now. The code relies on idea to assign to paragraphs their major modes, i.e., list items form a lists, table heading, rows, and separators form a table and so on. This decision allowed me to handle open and close tags carefully, when paragraph can open its major mode, but can't close its major mode.  The code includes one method only for managing indentation and that for managing output accumulation. In common, it made the code clearly, which in turn handles all examples correctly.

One obvious difference: blank lines don't get accumulated any more, because I decided to restore the default Emacs Org mode behavior when two blank lines close all modes. 

Best regards,
Vladimir.

### CODE REVIEW

**Comment by wallyqs** [comment]
Hey Vladimir, thanks for sharing you work again. I think you really nailed it by refactoring into major modes, this looks really good and it makes things more clear. Thanks for handling the code syntax highlight test too!
Awesome pull request.

**Comment by vonavi** [comment]
Hey, guys!
I completed the work on indentation, when I refactored methods for accumulating output and the maintenance of mode stack. A lot of code was modified, so now I satisfied with the results, in particular, the HTML output. All examples were updated accordingly. I'm looking forward to answer if you accept the pull request or not.
Best regards,
Vladimir.

**Comment by wallyqs** [comment]
Hey Vladimir,

Thanks for your contribution. I will be looking into pulling this over the weekend.
Cheers.

**Comment by wallyqs** [comment]
Merged. I like the direction you are taking with refactoring this gem. This also fixed some bugs that the gem had regarding lists, so thanks again for your contribution.

**Pull request closed without merging**
