### PR TITLE
Support for <hr> for HTML

### PR DESCRIPTION
**Pull request by Neil-Smithline**
Hey,

I am interested in beefing up Github's support for README.org support.

My understanding is that this uses the org-ruby gem. Is that correct?

I have assumed that it uses the HTML conversion of org-ruby and not the textile conversion. Is that correct? [EDIT @ 15:39 ET, 26 Feb 2013 - This is correct per code at https://github.com/github/markup/blob/master/lib/github/markups.rb]

Based on the above assumptions, I have started looking at the org-ruby support for HTML. I'm struggling a bit as I've even seen Ruby code before last night, but I'm learning.

I added support for converting 5 or more consecutive '-' alone on a line with nothing else but whitespace into an HTML <hr>. tag. It is a one line. I have not made any change to the textile support as I made the change in html_output_buffer.rb. 

I thought it may have been better to put it into line.rb by creating a :horizontal_rule paragraph type but I couldn't figure out how to do that. 

I'm interested in doing more. Particularly, I would like #+HTML: and #+BEGIN/END_HTML to work as well as having "@<html-tag and properties>" be translated to "<html-tag and properties>" in the output.

My thought on the @< fix is that I need to change the gsub in html_output_buffer.rb that converts < to &lt; to not do that if it is preceded by an @. Then I need to conjure up a magical regexp for the gsub that converts > to &gt; such that it won't do it if this is the first > following a @<. 

Does my change seem reasonable? Do my future plans seem reasonable? Are you good with me doing this? Should I have implemented something differently?

Thanks,

Neil

PS: I haven't quite figured out how line.rb works as I really don't know Ruby, but it looks like a very nice piece of code.

### CODE REVIEW

**Comment by Neil-Smithline** [comment]
You also had a very sparse TAGS file. I updated it, added a TAGS-README.org explaining how I created it, and added TAGS-README.html to the .gitignorefile.

I wasn't sure why the TAGS file was checked in but I thought that if there was one that it should be richer than the one that's in the repo.

**Comment by wallyqs** [comment]
Neil, thanks for your patch.

You are right in that this should fit better on `line.rb`. I think that the approach here would be to add a `horizontal_rule?`  method to the class that tries to match the regexp you wrote, add this to the `paragraph_type` check, and then modify the `html_output_buffer#flush!` to output "&lt;hr /&gt;" given that paragraph_type. 
If implemented this way, then to add the equivalent functionality for textile output, we only have to modify the `textile_output_buffer#flush!` method.

**Comment by Neil-Smithline** [comment]
OK. So I figure out what you said about line.rb, implement it in line.rb and html_output_buffer#flush! and give you another pull request. You, at your leisure, will add the textile_output_buffer#flush! functionality. Correct?

Also, I'm wondering if you know what version of your gem that Github is using. I've seen that they say they're using your gem but they don't give the version number. I have a feeling that they're using version not-very-recent :-)

Thanks

**Comment by wallyqs** [comment]
Yes, that is right. :)

About Github version ,their github/markup project's Gemfile does not specify the version, so I would expect that they are using the latest one released to Rubygems which is 0.6.0. 

https://github.com/github/markup/blob/master/Gemfile

**Comment by Neil-Smithline** [comment]
When looking at the suggested change I noticed that the function line#plain_text? isn't used. Is that just dead code? Is it easier if I remove it or leave it?

**Comment by wallyqs** [comment]
If it is not used (and after confirming that the tests still pass) I can't see a reason to keep it. 

UPDATE: I ran the tests and removing the `line#plain_text?` check, seems to break the footnotes support for HTML.

**Comment by Neil-Smithline** [comment]
Speaking of tests.... How do I run them? I added some clauses for the `<hr>` tag but don't know how to run the tests (have I have mentioned that I don't know Ruby?).

PS: I think it is great that you have all these tests. Quite disciplined.

**Comment by wallyqs** [comment]
You can run the tests with `rake spec`.
Also check out `rake -T` to get a list of other tasks.

https://github.com/bdewey/org-ruby/wiki/When-adding-a-new-feature

**Comment by Neil-Smithline** [comment]
I finally got the !#@#$ tests to run. I spent more time getting the Rakefile to run than I did on the change :-|

_Horizontal Rule Status_:
- Change to `line.rb` for new `horizontal_rule` type.
- Change to `html_output_buffer.rb` to handle new type.
- Created a `horizontal_rule.{org,html}` test files.
- Modified `line_spec.rb` to test the new functionality (really glad I did this - I wasn't handling tabs correctly).
- _No_ change to `textile_output_buffer.rb` for the new type as you agreed to handle that.

_Other Changes_:
- An updated `TAGS` file that is complete or close to it. I do not feel strongly if you do not wish to pull this file. Being as I don't understand why there is a `TAGS` file in the repo, I can't be sure I've made an improvement.
- A modified `Rakefile`. (No strong feelings on this file either.) The changes I made were all noob Rakefile/Ruby. I added more error checking. Being as I don't know or use Ruby, I needed to install several gems. I think most Ruby programmers would have them installed but I see no reason not to test for them and print a useful error message. This way the next noob won't have to google as much as I had to. I also beefed up the text of the error messages to help the next noob. 

Thanks for supporting me through this. You may say that I've now popped my ruby-red cherry :-)

Neil

PS: I've only touched Ruby but I think I like it. It seems more declarative than most languages yet doesn't seem to overburden the user with too much type checking. I also like the inline syntactic description of entities (eg: trailing `?` and leading `@`). Makes it hard to get a type wrong and really easy for Emacs syntax checking.

PPS: Perhaps there should be a Rakefile rule to generate the `TAGS` file? I'm not sure how to do it but it shouldn't be hard.

**Comment by wallyqs** [comment]
Neil, thanks for the patch. I'm sorry to hear that you had a bad time installing the gems to run the tests.
For this a `Gemfile` is usually included on the repository that you `bundle install` to resolve these dependencies.
I included one on the version I'm developing: https://github.com/wallyqs/org-ruby/blob/master/Gemfile but I'll consider including it here too.

**Comment by Neil-Smithline** [comment]
No need to apologize. I'm learning Ruby and learning about `Rakefiles`, `Gems`, and now `Gemfiles` (I have a guess but I'll have to figure out what they are) is all part of the learning.

And, as I said earlier, because of your testing framework, I found it easy to add a feature test (ie: `horizontal_rule.rb` file) and unit tests to `line_spec.rb`. And one of my unit test failed. I just love it when I fix the bugs before I ship the code.

The next thing I've been thinking about is adding parsing of the `@<html-tag>` syntax to the gem. That seems a significantly more complicated task. That's fine by me as that means significantly more learning. But I think I see a problem.

`html_output_buffer.rb#flush!` begins by calling `escape_buffer!`. That preprocesses `&`, `<`, and `>`. So I think my change will have to be made to `escape_buffer!`. But the end of `flush!` calls `special_symbols_to_html` which also modifies `&`, `<`, and `>`.  I think that will remove any HTML I've included.

From looking at the code, I think that the duplicate handling of the three characters is currently not a problem in the current gem but will likely become a problem for me when I add the `@<` processing. I'll run tests before proceeding but wonder if you foresee any harm in me removing the processing of `&`, `<`, and `>` from `special_symbols_to_html`?

Thanks, 
Neil

PS: If you're going to give me credit on the `org-ruby` gem, adding a link to http://www.neilsmithline.com would be appreciated.

**Comment by Neil-Smithline** [comment]
Been thinking more about handling `@<html-tag>` and have come up with what I think is an elegant solution but I'm not sure about the performance cost of doing it. Looking for your thoughts.

In `parser.rb` I would scan for the `@<` wherever it is treated specially. When I find an `@<` I would break the line at the `@<` and insert a new line into the `lines` array. The newline will contain everything from the `@<` to the `>' but I'd replace the`@`with`#+HTML: `.

Once that is done, handling this becomes easy. I haven't thought the details out but using an existing or creating a new line type in `line.rb` is probably the way to go.

The advantages of this solution are:
- It identifies the special syntax early in the parsing. This prevents problems such as unintentionally escaping `<`. 
- It builds on the existing concept of line types/modes.
- For free we'll handle `#+HTML:` lines as well. Two for the price of one.

My only concern with this strategy is the cost of inserting a new entry into the middle of the `lines` array. As I don't really no Ruby, I have no idea how efficient Ruby's `Array#insert` method is. I imagine that this won't be a problem but I want to check with you before you do it. I guess you can come back with one of three answers (1) No way Neil! That will be way to sloooowww. (2) Sounds like a good idea; why don't you give it a try. (3) I have no idea. Can you write a performance test to see what numbers you get?

Thanks,

Neil

**Pull request closed without merging**
