### PR TITLE
Fix for definition lists.

### PR DESCRIPTION
**Pull request by vonavi**
Hey!
I made a mistake with handling definition lists. It's seen from an example where paragraphs within the definition list have colons `::`, for instance,

```
 + Key :: Value :: Still value (k1)
   Paragraph :: with :: no value
 + Key :: Value :: Still value (k1) ::
   Paragraph :: with :: no value ::
 + ::
   Paragraph :: with :: no value
```

I fixed this mistake and added case with no definition given which in turn is replaced with `???` (the last list). Output:

``` html
<dl>
  <dt>Key :: Value</dt><dd>Still value (k1)
    Paragraph :: with :: no value</dd>
  <dt>Key :: Value :: Still value (k1)</dt><dd>
    Paragraph :: with :: no value ::</dd>
  <dt>???</dt><dd>
    Paragraph :: with :: no value</dd>
</dl>
```

**UPD.** The examples were checked as well.

### CODE REVIEW

**Comment by vonavi** [comment]
Hey Wally!
Can you create an org-ruby gem? It's important for me to see the results of work as a gem. On my opinion, the current code is good enough.
Best regards,
Vladimir.

**Comment by wallyqs** [comment]
Yes, working on it! Should be up in a few hours, really thanks.

**Comment by wallyqs** [comment]
Hey Vladimir, I just released the gem as version 0.8.0 since you significantly improved it and introduced many changes. I think this should be a great release of the gem :beers: 
Thanks,
Wally

**Comment by vonavi** [comment]
Thanks a lot! The only remark is that the date of v0.8.0 at [RubyGems](https://rubygems.org/gems/org-ruby) is October 7, 2012.
Best regards,
Vladimir.

**Comment by wallyqs** [comment]
Yes... I missed that one. I will fix it in the next patch release.

**Pull request merged**
