### PR TITLE
Support of HTML source block added.

### PR DESCRIPTION
**Pull request by vonavi**
Hey!
It's again me :) This code provides the support of HTML source blocks. The examples were checked.
Best regards,
Vladimir.

### CODE REVIEW

**Comment by vonavi** [comment]
Hey!

There are new changes. First, HTML tags can be used if they are marked with `@` in accordance with [Quoting HTML tags](http://orgmode.org/manual/Quoting-HTML-tags.html). Second, formatting images to both HTML and Textile formats was turned to the default Org-mode behavior. It significantly modifies the previous behavior, however, it gives the possibility to use as inline images as links, and corresponds to the Org-mode manual: [Images in HTML export](http://orgmode.org/manual/Images-in-HTML-export.html).

For instance, Org-mode source

```
* Links and images

- [[http://google.com]]
- [[http://google.com][Google]]
- [[http://image.jpg]]
- [[http://image.jpg][image description]]
- [[http://image.jpg][file:thumb.jpg]]
- [[http://google.com][file:thumb.jpg]]
```

produces the following HTML output:

``` html
<h1>Links and images</h1>
<ul>
  <li><a href="http://google.com">http://google.com</a></li>
  <li><a href="http://google.com">Google</a></li>
  <li><img src="http://image.jpg" alt="http://image.jpg" /></li>
  <li><a href="http://image.jpg">image description</a></li>
  <li><a href="http://image.jpg"><img src="thumb.jpg" alt="thumb.jpg" /></a></li>
  <li><a href="http://google.com"><img src="thumb.jpg" alt="thumb.jpg" /></a></li>
  <li><img src="http://image.jpg" alt="http://image.jpg" /></li>
  <li><a href="thumb.jpg"><img src="thumb.jpg" alt="thumb.jpg" /></a></li>
  <li><a href="thumb.jpg">image description</a></li>
  <li><a href="hz.html">description</a></li>
</ul>
```

Best regards,
Vladimir.

**Comment by vonavi** [comment]
I updated the example from the last comment in accordance with the current code stage.

**Comment by wallyqs** [comment]
Hey Vladimir, big changes are welcome. Specs are ok and it looks good so I merged it. I think this is going to be a good release of the gem, thanks for helping out.

**Comment by vonavi** [comment]
No prob. I had fun working on this gem :smile:

**Pull request merged**
