### PR TITLE
Link abbrev feature

### PR DESCRIPTION
**Pull request by pierre-lecocq**
Hi,

As requested in issue #52, I now manage link abbreviations.
Tell me if the logic is ok for you.

Here is an Org example:

```
#+LINK: example http://example.com/something
#+LINK: example2 http://example.com/something2

[[example][This an example]]
[[example2][This is the second example]]
[[http://example.com/standard][Standard example]]
```

this is the end

### CODE REVIEW

**Comment by wallyqs** [comment]
Thanks again! Can you also update the links example here?
https://raw.github.com/pierre-lecocq/org-ruby/master/spec/html_examples/link-features.org
You can update the example with this then commit the changes.

```
rake testcase:accept[link-features]
```

**Comment by pierre-lecocq** [comment]
Done !

commit f05b079e92211d4ef574211642b0d11d84e5ee13

**Comment by wallyqs** [comment]
Looks good to me. Thanks :)

**Comment by pierre-lecocq** [comment]
Thanks @wallyqs !

**Pull request merged**
