### PR TITLE
Correct parsing of org-mode emphasis

### PR DESCRIPTION
**Pull request by vonavi**
The code follows Emacs' org-mode parsing of emphasized text as close as possible. It relies on Emacs' org-mode code, which I enclose with slight modifications. I combine regexp `org-emph-re`

``` scheme
(setq org-emph-re
      (concat "\\([" pre "]\\|^\\)"
              "\\("
              "\\([" markers "]\\)"
              "\\("
              "[^" border "]\\|"
              "[^" border "]"
              body1
              "[^" border "]"
              "\\)"
              "\\3\\)"
              "\\([" post "]\\|$\\)"))
```

with emphazing procedure in `org-html.el`

``` scheme
(defun org-export-html-convert-emphasize (string)
  "Apply emphasis."
  (let ((s 0) rpl)
    (while (string-match org-emph-re string s)
      (if (not (equal
                ;; Return preceding marker
                (substring string (match-beginning 3) (1+ (match-beginning 3)))
                ;; Return char after preceding marker
                (substring string (match-beginning 4) (1+ (match-beginning 4)))))

          ;; If preceding marker and the following char are different
          ;; Set position `s' to the regexp beginning
          (setq s (match-beginning 0)
                rpl
                (concat
                 ;; Leave pre_emphasis unchanged
                 (match-string 1 string)
                 ;; Replace preceding marker by the corresponding open tag
                 (nth 2 (assoc (match-string 3 string) org-emphasis-alist))
                 ;; Leave body unchanged
                 (match-string 4 string)
                 ;; Replace posterior marker by the corresponding close tag
                 (nth 3 (assoc (match-string 3 string)
                               org-emphasis-alist))
                 ;; Leave post_emphasis unchanged
                 (match-string 5 string))
                ;; Incorporate changes into the primary string
                string (replace-match rpl t t string)
                ;; Adjust position `s' to the next regexp search
                s (+ s (- (length rpl) 2)))

        ;; If preceding marker and the following char are the same
        ;; Do nothing, go forward
        (setq s (1+ s))))
    string))
```

Newlines within emphasis follows from

``` scheme
(setq e org-emphasis-regexp-components)
(setq body (nth 3 e))
(setq nl (nth 4 e))
(setq body1 (concat body "*?"))

(if (> nl 0)
    (setq body1 (concat body1 "\\(?:\n" body "*?\\)\\{0,"
                        (int-to-string nl) "\\}")))
```

### CODE REVIEW

**Comment by wallyqs** [comment]
Thanks a lot for this patch. This fixes many things
that were happening on the output when mixing different kind of emphasis
in the same line. (I included a testcase for this here: https://github.com/bdewey/org-ruby/commit/b4add3f5d828cedd2989d396e4a405346f842e78)

One note about the =newline= support, I think that we can probably
overlook this feature since in org-ruby we are applying emphasis 
per paragraph all the time, even though this causes a 
small difference between the default output from emacs-lisp exporter.

For example, considering this text:

```
*Starting the line here
*and continuing here
to close**
```

In Emacs, by default we have =number of newlines allowed= set to 1,
in the Org Appearance::Org Emphasis Regexp Components group, which means
that it will be exported as:

```
<p>
*Starting the line here 
<b>and continuing here to close*</b>
</p>
```

While in =org-ruby= we get:

```
<p><b>Starting the line here *and continuing here to close*</b></p>
```

which is the same output as setting =number of newlines allowed= to 2 in Emacs.

```
<p>
<b>Starting the line here  *and continuing here to close*</b>
</p>
```

In other words, in org-ruby it is as if we were setting =number of newlines allowed=
dynamically to the number of lines in the paragraph. (Though what is actually happening
is that in org-ruby by the time we are emphasizing the text, we have already removed
all the newlines so we only need to emphasize one line).

One case that is possible in Emacs and not possible in org-ruby is the following:

```
*Starting the line here

*and continuing here
to close**
```

If we set =number of newlines allowed= in Emacs to 3,
this would be rendered as:

```
<p>
<b>Starting the line here   *and continuing here to close*</b>
</p>
```

while in org-ruby we consider this as 2 different paragraphs: 

```
<p>*Starting the line here</p>
<p><b>and continuing here to close*</b></p>
```

For this case, I would like to keep things simple and apply emphasis per paragraph,
where one paragraph are blocks of lines separated by 2 line breaks.

**Comment by vonavi** [comment]
Thank you a lot for the explanation. If the number of newlines allowed is more than one, Emacs' behavior is buggy, producing even different output for HTML and LaTeX formats. On my opinion, it is better to have one instance such as a paragraph, removing newlines. I'll resend my patch after a revision.

Sometimes, I'm unhappy with that how Emacs emphasizes a text. At least one missing thing is an escape character. That is why I'm trying to keep an emphasized text simple and intuitively clear. I don't have an intuitive meaning about your first example, but I agree that the lack or presence of a newline should not make sense. Then `auto-fill-mode` and `longlines-mode` in Emacs have the similar behavior.

Is there way to introduce an escape character in org-ruby? I know that it is not intuitive, and is not supported in Emacs. Moreover, I guess that anybody may lose the ease of working process in org-mode if he should thing about the escaping of chars. But I would like to know your opinion.

**UPD.** I'm going to have a look at org-ruby's regexps. My opinion is that org-ruby should follow org-mode as close as possible. It relates to an output as well. But it is not clear for me why you avoid newlines from output. I would like to keep all newlines, letting the customer to make a decision about newlines and preferred Emacs' mode (`auto-fill-mode` or `longlines-mode`).

**Comment by vonavi** [comment]
Oops, GitHub doesn't allow to cancel a pull request. If you disregard my pull request, I will send a new one with a revision done. Or you can see the corresponding commit in my fork of org-ruby.
**UPD.** I see that the revision done in my fork has been reflected in the pull request automatically.

**Comment by wallyqs** [comment]
Merged! Thanks!

**Pull request merged**
