### PR TITLE
Fix regexps for replacing Org-mode entities.

### PR DESCRIPTION
**Pull request by vonavi**
Hey!

This code modifies the replacement of Org-mode entities. First, I don't check regexps for all entities, which should take a much shorter time that it was before. I took proper regexp from original `org.el` (see function `org-fontify-entities`). Second, no need to close every Org-mode entity by `{}`, instead, the default Org-mode behavior is used. I re-created file `gen-special-replace.el` to automatically generate files for the replacement of Org-mode entities. Can you create an example for Org-mode entities to ensure that the code works right?

**P.S.** I'm looking forward a new release, but I would like to add some code before that. I wish to use direct HTML code with lines `#+html:HTML_code`. In addition, maybe I'll take a look at issue #30 and some other improvements. In any way, I'll tell you if I realize these ideas.

Best regards,
Vladimir.

### CODE REVIEW

**Comment by vonavi** [comment]
Hey!

I've finished job that I mentioned in the previous comment, and I'm satisfied with the current status of Org-ruby. Last changes are the following:
1. Fix for definition lists which closes #30.
2. Text withing a code emphasis is kept as is.
3. Raw HTML can be incorporated with option #+html.

Best regards,
Vladimir.

**Comment by vonavi** [comment]
I checked the current code with Ruby versions 1.9.3, 1.8.7. Everything is OK.

**Comment by wallyqs** [comment]
Hey Vladimir, I'm still checking the changes you made and plan to merge it tomorrow. Many thanks for the bug fixes, the parser has become much better with your contributions.

**Comment by vonavi** [comment]
Hey, Waldemar!
Very good! I only changed two lines just now in order to better accumulate lines with `#+html`.
Best regards,
Vladimir.

**Pull request merged**
